kyndryl-design-system/shidoka-applications

.storybook/main.js
package-lock.json
package.json
src/components/global/footer/footer.stories.js
src/components/global/header/Header.stories.js
src/components/global/uiShell/uiShell.stories.js

Replaced `storybook-addon-designs` with the new official `@storybook/addon-designs` plugin for embedding Figma designs.

docs(storybook): use new addon-designs plugin

---

src/components/reusable/checkbox/checkboxGroup.ts
src/components/reusable/datePicker/datepicker.ts
src/components/reusable/daterangepicker/daterangepicker.ts
src/components/reusable/dropdown/dropdown.ts
src/components/reusable/radioButton/radioButtonGroup.ts
src/components/reusable/textArea/textArea.ts
src/components/reusable/textInput/textInput.ts
src/components/reusable/timepicker/timepicker.ts

1. Changed validation message property set to internal so that consumer can provide their own validation message via **invalidText** prop.
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1322887/

fix: Form invalid text internal messages for all form elements

---

src/components/reusable/dropdown/dropdown.scss

Dropdown options were taking up space on the page when hidden due to CSS visibility. Set height to 0 to prevent this.

fix(dropdown): remove height when closed

---

src/components/global/header/header.ts

The mobile header-nav will now close when tapping outside out it, resolves #31

fix(header): close mobile nav on click out, resolves #31

---

src/components/reusable/dropdown/dropdown.scss
src/components/reusable/dropdown/dropdownOption.scss

Hopefully resolves #37 @guptaashray
The issue seemed to be the .options height changing, which is unnecessary with visibility property.
I still could not reproduce the initial selection text not showing, or the multi-select tags text not showing.

fix(dropdown-option): mac chrome visibility issue

---

src/components/reusable/modal/modal.scss
src/components/reusable/modal/modal.ts

- Browsers that don't support discrete transitions will animate in, but not animate out. 
- Browsers that do support it will get both. 
- Once a browser adds support, it will be automatic.
- Changed transition/animation duration to 400ms.

fix(modal): add discrete transitions for supported browsers

---

src/components/reusable/sideDrawer/sideDrawer.scss

- While closing drawer it's height getting cut and then it's being closed
- If you see carefully while closing drawer, firstly the height of drawer is reduced and then it's getting closed. I fixed by setting `min-height: 100vh`; to `dialog` style
https://github.com/kyndryl-design-system/shidoka-applications/assets/140634142/05c14d5b-63ae-4a63-ad7b-5a5da38f52af

fix(style): Dialog height while drawer is closing

---

src/components/reusable/table/story-helpers/column-setting.ts

- Raised by Jaideep M V when we scroll the row then it overlaps the header and shows lock icon and checkbox. 
- Resolved by setting z-index

fix(table-setting): hide column checkbox and lock icon when scroll

---

src/components/reusable/tooltip/tooltip.ts

**RCA**
Event listeners were not getting emitted on-tooltip-toggle due to typo of text "open" which was used on updated() method to _emitToggle() based on conditional check.
**Solution**
Update the text "open" to "_open" which solves the emit toggle action.
**Before Fix**
**After Fix**

fix(Tooltip): on-tooltip-toggle emit event listeners

---

custom-elements.json
src/components/reusable/modal/modal.stories.js
src/components/reusable/modal/modal.ts

**RCA:** 
Using VoiceOver Modal - Close button is not read as Close Button, it just reads as Button
**Solution :** 
Added "aria-lable" to the  close button icon to get identified by the voice over .
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1904497
Use system Voiceover to test this fix
https://github.com/user-attachments/assets/ec280463-fda6-4186-81e4-5d451a095d58

fix(modal): close button accessibility label

---

src/components/global/header/headerFlyout.scss
src/components/global/header/headerLink.scss
src/components/global/localNav/localNavLink.scss
src/components/reusable/dropdown/dropdown.scss
src/components/reusable/modal/modal.scss
src/components/reusable/notification/notification.scss
src/components/reusable/overflowMenu/overflowMenu.scss
src/components/reusable/search/search.scss
src/components/reusable/sideDrawer/sideDrawer.scss
src/components/reusable/stepper/stepperItem.scss

`transfrom`s create a bounding context which throws off the placement of absolute and fixed position elements. Example: using a Tooltip inside of a Modal. Switching the open states to `transform: none` maintains the transitions/animations while also removing that bounding context.

fix: remove unnecessary bounding contexts created by transforms

---

src/components/reusable/textArea/textArea.scss
src/components/reusable/textArea/textArea.ts
src/components/reusable/textInput/textInput.scss
src/components/reusable/textInput/textInput.ts

Moved char counter below the Text Area.
Add char counter below the Text Input and only show counter when maxLength is provided.
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1918161

feat: counter for textArea and textInput

---

.storybook/global.scss
package-lock.json
package.json
rollup.config.js
src/common/helpers/swiper.ts
src/common/scss/utility/gridstack-shidoka.scss
src/common/scss/utility/swiper-shidoka.scss
src/components/reusable/widget/Gridstack.mdx
src/index.ts
src/stories/carousel/Docs.mdx
src/stories/carousel/carousel.stories.js

Added Shidoka default configuration and stylesheet for [Swiper](https://swiperjs.com/), with example Stories and usage documentation.
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1904441/
https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/Applications---Component-Library?node-id=16511-29991&node-type=frame&m=dev
**Note:** Some things have been tweaked slightly and are not reflected in Figma yet. Notably:
- Fractional paging
- Tab styles
- Off-screen slide de-saturation

feat(carousel): add shidoka swiper config, styles, examples

---

src/components/reusable/notification/notification.scss
src/components/reusable/notification/notificationContainer.scss
src/components/reusable/tag/tag.scss

Changed the type mixin for tag text and notification's timeStamp text to have `font-size: 14px`.
[TASK 1907198](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1907198)

fix(tags,notificaiton): Minor accessiblity updates for tags and notificaiton components

---

src/components/reusable/tabs/tab.scss

Adjust Tabs background color to be transparent so it can be used on light-gray backgrounds as well as white. 
Changes include:
- Line style default BG
- Line style disabled:hover BG
- Contained style selected/active BG

fix(tabs): transparent background instead of white

---

custom-elements.json
src/components/reusable/stepper/stepper.scss
src/components/reusable/stepper/stepper.stories.js
src/components/reusable/stepper/stepper.ts
src/components/reusable/stepper/stepperItem.scss
src/components/reusable/stepper/stepperItem.ts
src/components/reusable/stepper/stepperItemChild.ts

A bug was raised that stepper item title links could not be controlled by the application. This PR accomplishes the following:
1. Added a component prop so a link href can be passed to stepper items/children.
2. Step Title will render as plain text if no link is provided.
3. Link href value added to click event details.
4. Child step items will now always be accessible/expandable even when the parent step is not in active state.

fix(stepper): add support for link url values on stepper items

---

src/components/global/header/header.scss
src/components/global/localNav/localNav.scss

Corrected an alignment issue where the Header logo had too much space on the left side when the nav menu was absent, particularly at mobile sizes.
[Initial report reference link](https://teams.microsoft.com/l/message/19:m15yXA3kC7fl9TvnIML-6DxhfDtwyoLJMu0nVAeddXQ1@thread.tacv2/1730837559654?tenantId=f260df36-bc43-424c-8f44-c85226657b01&groupId=6097bcb7-eb77-4588-9226-1430b9c803ab&parentMessageId=1730837559654&teamName=Shidoka%20Design%20System&channelName=General&createdTime=1730837559654)

fix(header): alignment of logo when nav menu is absent

---

custom-elements.json
src/components/reusable/loaders/skeleton.scss
src/components/reusable/loaders/skeleton.stories.js
src/components/reusable/loaders/skeleton.ts

-Added lines props into skeleton to provide more flexibility to use skeleton as multiple times.
- lines(default  to 1) property control's how many number of skeleton to be shown
[USER STORY 1995481](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1995481)

feat(skeleton): added lines props for skeleton

---

src/common/scss/form-input.scss
src/components/reusable/textInput/textInput.scss

Fixed the disabled form input styles so the border color doesn't change on hover, and the text input icon uses the disabled text color.

fix: disabled input hover & icon color

---

custom-elements.json
src/components/reusable/globalFilter/globalFilter.skeleton.sample.ts
src/components/reusable/globalFilter/globalFilter.stories.js
src/components/reusable/loaders/skeleton.scss
src/components/reusable/loaders/skeleton.stories.js
src/components/reusable/loaders/skeleton.ts
src/components/reusable/table/table.skeleton.ts
src/components/reusable/table/table.stories.ts
src/components/reusable/tag/tag.skeleton.ts
src/components/reusable/tag/tagGroup.stories.js

Updated Data Table and Tags skeleton as per Figma
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1991926)
https://www.figma.com/design/2Vgr8KRWwtJiCETolv0zNE/1.12-Rio-De-Janeiro?node-id=92-52399&node-type=instance&m=dev

feat: updated data table and tags skeleton pattern

---

src/components/reusable/dropdown/dropdown.scss
src/components/reusable/dropdown/dropdown.ts

Resolves #289. 
Clear button (X) will now appear disabled and will not be clickable.

fix(dropdown): disable clear button correctly

---

custom-elements.json
src/components/reusable/overflowMenu/overflowMenuItem.scss

In Light theme : On hover of overflow menu item was not getting highlighted.
[BUG 2045363](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2045363)
- [] Ran the `analyze` command to update Storybook docs.

fix(Overflow): hover state fix

---

src/components/reusable/checkbox/checkbox.scss

Original checkbox color tokens, particularly border tokens, across states were confusing. Corrects `--kd-color-border-ui-default` to instead use `--kd-color-border-forms-default`
Changes were made to:
- border color for unhovered, unchecked state
- border color for focused, unhovered
[Bug 2045697](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2045697)
[Checkbox figma updates](https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/branch/qMpff4GuFUEcsMUkvacS3U/Applications---Component-Library?node-id=21764-759094&focus-id=21764-759091&m=dev)
- can go here
1. unchecked, unhovered
2. hovered, unchecked
3. focus, unchecked

fix(checkbox): additional dark mode token updates

---

custom-elements.json
package-lock.json
package.json
src/common/scss/form-input.scss
src/components/reusable/dropdown/dropdown.ts
src/components/reusable/numberInput/numberInput.scss
src/components/reusable/numberInput/numberInput.ts
src/components/reusable/progressBar/progressBar.ts
src/components/reusable/radioButton/radioButtonGroup.ts
src/components/reusable/textArea/textArea.scss
src/components/reusable/textArea/textArea.ts
src/components/reusable/textInput/textInput.scss
src/components/reusable/textInput/textInput.ts

UX made updates to some global input styles as well as number input-specific styles.
- updated foundation package
- set +/- incrementing buttons to `primary-app` kind with `outlineOnly`
- convert global form input text color to `--kd-color-text-level-primary`
- convert global form input default border-color to `--kd-color-border-forms-default`
- convert global form input **invalid** state border-color to `--kd-color-border-variants-destructive`
- convert global form input error message text color to `--kd-color-text-variant-destructive`
- update errorIcon across all form components to use the error filled icon instead of warning
- utilize form-input.scss for border styling across form inputs (excludes dropdown `.select` for now)
- some minor typescript corrections
N/A
[Updated Number …

fix(form components): ux dark mode updates

---

src/common/scss/form-input.scss
src/components/reusable/textInput/textInput.scss

**kd-color--text-level-disabled**  currently not exists in foundation.
Text Input caption and Icon disabled state color token updated
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2041670
https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/branch/qMpff4GuFUEcsMUkvacS3U/Applications---Component-Library?node-id=4291-236773&m=dev

fix(formTextInput): updated caption and icon color token

---

src/components/reusable/progressBar/progressBar.scss

Updated colour tokens as per the UX.
[TASK 2003578](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003578)
[Progress bar](https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/branch/qMpff4GuFUEcsMUkvacS3U/Applications---Component-Library?node-id=19723-26651&node-type=canvas&m=dev)
Updated the colour tokens for the following components
- Progress bar

feat(progress bar): colour token updates

---

custom-elements.json
src/components/reusable/tag/tag.scss
src/components/reusable/tag/tag.skeleton.ts
src/components/reusable/tag/tag.stories.js
src/components/reusable/tag/tag.ts
src/components/reusable/tag/tagGroup.scss
src/components/reusable/tag/tagGroup.stories.js
src/components/reusable/tag/tagGroup.ts
src/stories/migration.mdx

**Tag component**
- Color token updates.
- New clickable variant.
[TASK 2003572](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003572)
[Tag component](https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/branch/qMpff4GuFUEcsMUkvacS3U/Applications---Component-Library?node-id=21797-44503&m=dev)

feat(tag): colour token updates

---

src/components/reusable/textInput/textInput.scss

Display right icon with clear icon
https://github.com/kyndryl-design-system/shidoka-applications/issues/304

fix(TextInput): icon right with clear icon fix

---

src/components/reusable/overflowMenu/overflowMenu.scss
src/components/reusable/overflowMenu/overflowMenu.ts
src/components/reusable/table/story-helpers/action-menu.sample.ts
src/components/reusable/table/table.stories.ts

Fixed position overflow menu horizontal position was incorrect when inside a scrollable container. Adjusting positioning logic to calculate it correctly when opened.
- Go to Data Table > Sticky Header story
- Shrink the screen so a horizontal scrollbar appears on the table
- Scroll the table right
- Open a row overflow menu, it should be positioned correctly with the anchor button

fix(overflow-menu): correct fixed horizontal position

---

src/stories/sampleCardComponents/vitalCard.sample.ts
src/stories/sampleCardComponents/vitalCard.scss
src/stories/vitalCard.stories.js

Fixes [AB#2102137](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2102137)
Added a card pattern which has tooltip(info icon) along with title.

feat: card with title tooltip pattern

---

src/components/reusable/accordion/accordionItem.scss

Accordion
- changed the subtitle colour token to `text-level-primary`
Changes done as per - [2.0 color test](https://kyndryl-my.sharepoint.com/:x:/r/personal/brian_patrick3_kyndryl_com/_layouts/15/doc2.aspx?sourcedoc=%7Bb1d2f480-e50c-4442-8e85-18e65341e603%7D&action=edit&activeCell=%27Sheet1%27!I16&wdinitialsession=0af86b70-9e65-1016-d1ac-446ed40feca7&wdrldsc=4&wdrldc=1&wdrldr=AccessTokenExpiredWarningGatekeeperCookieMismatch%2C)

fix(accordion): subtitle accessibility

---

src/components/reusable/table/story-helpers/table-story.sample.ts
src/components/reusable/table/table.ts

fixes #372
- Set `bubbles: false` on row selection events to avoid passing of the event to it's parent in case of [Nested table](https://shidoka-applications.netlify.app/?path=/story/components-data-table--nested-table)

fix(issue-372): event propagation fix for table row selection events

---

.github/workflows/build.yml
.github/workflows/release.yml

- Remove the ugly if statements from the Release job by separating it into it's own file.
- New Release workflow only runs on push to release channel branches.
- Make the Build workflow reusable so it can be called by the new Release workflow.
- Separated the Storybook build into it's own job.

ci: improve actions organization

---

package-lock.json
package.json
src/components/reusable/button/button.scss

Changed colour token for the following:
- Secondary destructive - hover & focused state -> text and background
- Outline destructive - hover state -> text
Fixes [AB#2124849](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2124849)
[Button](https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=20904-164714&m=dev)

fix(button): colour token changes

---

src/components/reusable/button/button.scss

Removed ` background-color` from `focus ` for secondary destructive button.
Fix for: https://github.com/kyndryl-design-system/shidoka-applications/pull/384/files/3ec6096e8d9a542bc729570ab880901fb5ef409d#r1965467261

fix(button): remove background-color from focus

---

custom-elements.json
src/common/helpers/flatpickr.ts
src/common/scss/shidoka-flatpickr-theme.scss
src/components/reusable/datePicker/datepicker.scss
src/components/reusable/datePicker/datepicker.stories.js
src/components/reusable/datePicker/datepicker.ts
src/components/reusable/daterangepicker/daterangepicker.scss
src/components/reusable/daterangepicker/daterangepicker.stories.js
src/components/reusable/daterangepicker/daterangepicker.ts
src/components/reusable/timepicker/timepicker.scss
src/components/reusable/timepicker/timepicker.stories.js
src/components/reusable/timepicker/timepicker.ts

fixes #400 
Add optional `staticPosition` prop to daterangepicker.ts, datepicker.ts, timepicker.ts -- when, `true`, this sets the `static` key-value in the Flatpickr options to append calendar UI to input,  otherwise defaulting the positioning as is currently the case on `main`
hierarchy:
1. `staticPosition` === true overrides everything
2. if a kyn-modal is detected, add a class `.container-modal` that will set the position to `fixed`
3. set position to `absolute` for default behavior -- flatpickr-calendar's open direction adjusts to the input's positioning on the page (perfect for regular form usage) [**default**]
- when `static: true` is set, the calendar UI is appended to the associated input, but there are some drawbacks. when the `staticPosition` prop is set to true, the …

fix(datepicker): append structure

---

custom-elements.json
src/components/reusable/tag/tag.scss

Added correct `background-color` for `active` state of all the tags.
fixes https://github.com/kyndryl-design-system/shidoka-applications/issues/414
fixes [AB#2148451](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2148451)
[Tags](https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=21813-327089&m=dev)

fix(tag): active state color update for clickable tags

---

src/common/helpers/flatpickr.ts
src/components/reusable/datePicker/datepicker.ts
src/components/reusable/daterangepicker/daterangepicker.ts
src/components/reusable/timepicker/timepicker.ts

1. From dev implementing date-range picker in his application:
"having a problem when I clear the dates from the input but then cancel the change. When I reopen the modal, I see the dates placeholder, not the dates, although there's a 'clear' icon there, so it appears it knows it has some value??"
to ensure that clear takes effect, we are now:
- resetting the component's internal state (value, defaultDate) to a cleared state
- calling Flatpickr's clear method and updating the input's value and ARIA label
- emitting the on-change event
- reinitializing Flatpickr's instance to ensure any dependent UI/state remains in sync after clear
2. dynamic language string wouldn't be accepted for `locale` prop, made more robust. handles errors with graceful fallback to 'en,' when needed

fix(datepicker): reinitialize on _handleClear, more robust locales

---

src/common/scss/form-input.scss
src/common/scss/shidoka-flatpickr-theme.scss
src/common/scss/utility/swiper-shidoka.scss
src/components/ai/aiLaunchButton/aiLaunchButton.scss
src/components/global/header/header-interactive.scss
src/components/global/header/headerLink.scss
src/components/global/header/headerPanelLink.scss
src/components/global/localNav/localNav.scss
src/components/global/localNav/localNavLink.scss
src/components/reusable/accordion/accordion.scss
src/components/reusable/accordion/accordionItem.scss
src/components/reusable/button/button.scss
src/components/reusable/card/card.scss
src/components/reusable/checkbox/checkbox.scss
src/components/reusable/checkbox/checkboxGroup.scss
src/components/reusable/dropdown/dropdown.scss
src/components/reusable/link/link.scss
src/components/reusable/numberInput/numberInput.scss
src/components/reusable/overflowMenu/overflowMenu.scss
src/components/reusable/overflowMenu/overflowMenuItem.scss
src/components/reusable/radioButton/radioButton.scss
src/components/reusable/search/search.scss
src/components/reusable/splitButton/splitButton.scss
src/components/reusable/table/story-helpers/column-setting.sample.ts
src/components/reusable/table/table-header.scss
src/components/reusable/tabs/tab.scss
src/components/reusable/tabs/tabs.scss
src/components/reusable/tag/tag.scss
src/components/reusable/toggleButton/toggleButton.scss
src/components/reusable/tooltip/tooltip.scss

Replace all instances of CSS `:focus` with `:focus-visible`. Prevents focus rings from appearing unnecessarily on click of many elements like Buttons/Tabs, but maintains focus state when needed for example on focused input elements and when keyboard tabbing. I did a batch replace all and have not looked at every affected component.
More info: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#focus_vs_focus-visible

fix: use focus-visible instead of focus

---

custom-elements.json
src/common/scss/utility/swiper-shidoka.scss
src/components/global/header/Header.stories.js
src/components/global/header/header-interactive.scss
src/components/global/header/headerCategory.scss
src/components/global/header/headerCategory.ts
src/components/global/header/headerFlyout.scss
src/components/global/header/headerLink.scss
src/components/global/header/headerLink.ts
src/components/global/localNav/localNav.scss
src/components/global/localNav/localNav.ts
src/components/global/localNav/localNavLink.scss
src/components/global/localNav/localNavLink.ts
src/components/global/uiShell/uiShell.stories.js

Overhauled navigation styles to match Figma designs.
fixes [AB#2181862](https://dev.azure.com/Kyndryl/f7f7ab25-06ec-43dc-902d-dee2e157cebd/_workitems/edit/2181862)
- [Component](https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=8471-347023&p=f&m=dev)
- [Patterns](https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=32254-77256&m=dev)
- Local Nav links use chevron icon instead of +/- for expand
- Local Nav links expanded/open state style changed to just bold text
- Header Link icon sizes normalized to 16px
- Minor spacing adjustments
- Local Nav pin button uses ghost style
- Added a prop to add left padding to links with no icon, used to align the text with links that do have an icon

fix(navigation): styles overhaul

---

src/components/reusable/daterangepicker/daterangepicker.ts

**ISSUE**: dateRangePicker only, when you select a range and then toggle `dateRangePickerDisabled` to true, it clears the selected `values` array to `[null, null]`
**SOLUTION**: prioritize `dateRangePickerDisabled` in `updated()` so that it only closes the flatpickr UI and no longer resets array
<br/>

fix(daterangepicker): values array clears on dateRangePickerDisabled toggle

---

custom-elements.json
package-lock.json
package.json
src/components/global/header/headerFlyout.scss
src/components/global/localNav/localNav.scss
src/components/global/localNav/localNavLink.scss
src/components/global/localNav/localNavLink.ts
src/components/reusable/tabs/tab.scss
src/components/reusable/tabs/tab.ts
src/components/reusable/tabs/tabs.scss
src/components/reusable/tabs/tabs.stories.js
src/components/reusable/tabs/tabs.ts

Got rid of the "Primary" tab style which was basically the same as secondary after recent changes.
fixes [AB#2184035](https://dev.azure.com/Kyndryl/f7f7ab25-06ec-43dc-902d-dee2e157cebd/_workitems/edit/2184035)
https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=7695-2822&p=f&m=dev

fix(tabs): remove tabStyle prop, only one style now

---

custom-elements.json
src/components/ai/sourcesFeedback/aiSourcesFeedback.ts

Sourcefeeadback Component 
Issue :  On multiple toggle of `Source`  button , Source text getting disappeared.
Browser : Safari
https://github.com/user-attachments/assets/7b01a962-f4e2-478b-8b8a-9235d438bd10
NA

fix(sourcefeeadback): source text visibility issue on Safari  on enter key hit

---

src/components/ai/sourcesFeedback/aiSourcesFeedback.ts

Added fix to bubble up on-toggle event from kyn-ai-sources-feedback component
[AB#2222370](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2222370)

fix: fix to bubble up on-toggle event from sources-feedback component

---

src/common/scss/form-input.scss
src/components/reusable/dropdown/dropdown.scss
src/components/reusable/numberInput/numberInput.scss

Focus state update for the following components are made:
1. Date and time pickers.
2. Text input.
3. Text area.
4. Search.
5. Dropdown.
6. Number input.
fixes [AB#2223639](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2223639)
[Focus state updates](https://www.figma.com/design/rC5XdRnXVbDmu3vPN8tJ4q/2.1-Edinburgh?node-id=5019-26666&m=dev)

fix: focus state update

---

src/common/scss/form-input.scss
src/components/reusable/checkbox/checkbox.scss
src/components/reusable/datePicker/datepicker.ts
src/components/reusable/daterangepicker/daterangepicker.ts
src/components/reusable/radioButton/radioButton.scss
src/components/reusable/timepicker/timepicker.ts
src/components/reusable/toggleButton/toggleButton.scss

Updated color tokens for below components in disabled state:
<body>
  | Disabled State
-- | --
Placeholder Text | --kd-color-text-level-disabled
Input Text | --kd-color-text-level-disabled
Label | --kd-color-text-level-disabled
Background | --kd-color-background-forms-disabled
Border | None
</body>
</html>
[AB#2213841](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2213841)
[Link here](https://www.figma.com/design/rC5XdRnXVbDmu3vPN8tJ4q/2.1-Edinburgh?node-id=4738-15997&p=f&m=dev)

feat: token updates for disabled state

---

src/components/reusable/dropdown/dropdown.scss

fix(dropdown): parellel tabbing focus fix

---

src/components/reusable/notification/notification.stories.js

In going over the changes from Edinburgh for documentation with Jimmy, I realized that the 'Toast' variant in the Notifications stories was missing a `success` status toast example. This is just adding that in.

fix: add missing success variant to toast notification story

---

src/components/reusable/dropdown/dropdown.ts

RCA: Dropdown: Due to cleartext props passed from `kyn-dropdwon` in`kyn-tag` makes tag label duplicated. 
Solution: 
Removed `cleartext` from `kyn-dropdwon` in`kyn-tag`.
fixes https://github.com/kyndryl-design-system/shidoka-applications/issues/454
NA
(if any)

fix(dropdown): multiple label fix on selected tags On hover

---

custom-elements.json
package-lock.json
package.json
src/components/reusable/tag/Docs.mdx
src/components/reusable/tag/tag.scss
src/components/reusable/tag/tag.stories.js
src/components/reusable/tag/tag.ts

Tag revamp.
fixes [AB#2136504](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2136504)
[Tag revamp](https://www.figma.com/design/rC5XdRnXVbDmu3vPN8tJ4q/2.1-Edinburgh?node-id=5095-25500&t=pH45wIspW27PoLrh-0)

feat(tag): tag revamp

---

custom-elements.json
package-lock.json
package.json
src/components/reusable/badge/badge.stories.js
src/components/reusable/badge/badge.ts
src/components/reusable/notification/notification.ts

Add prop to toggle icon visibility.
Replace status tags in notification with badges.
fixes [AB#2251153](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2251153)
[Badge](https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=34109-11236&p=f&m=dev)
[Notification](https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=9370-2442&m=dev)
- Check for working of new `hideIcon` prop added to badge component. By default, the icon is shown.
- Verify all the tags are replaced with badges in `default` and `clickable` notification.

fix(badge): add prop to toggle icon visibility

---

src/components/reusable/badge/badge.scss
src/components/reusable/tag/tag.scss

Increased the side padding for badge and tag from `4px` to `8px`.
NA
[Badge](https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=34109-11382&m=dev)
[Tag](https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=21792-35948&p=f&m=dev)

fix(badge-and-tag): Increased the side padding

---

src/components/reusable/dropdown/dropdownOption.scss
src/components/reusable/dropdown/dropdownOption.ts

Prevent selected option checkmark from overlapping option text.
[
Reported in Teams](https://teams.microsoft.com/l/message/19:m15yXA3kC7fl9TvnIML-6DxhfDtwyoLJMu0nVAeddXQ1@thread.tacv2/1747128195526?tenantId=f260df36-bc43-424c-8f44-c85226657b01&groupId=6097bcb7-eb77-4588-9226-1430b9c803ab&parentMessageId=1747128195526&teamName=Shidoka%20Design%20System&channelName=General&createdTime=1747128195526)

fix(dropdown-option): prevent checkmark text overlap

---

src/components/reusable/dropdown/dropdown.stories.js
src/components/reusable/dropdown/dropdown.ts
src/components/reusable/dropdown/dropdownOption.ts

A handful of fixes to work around selection/deselection when disabled and disabled + selected options are involved.
1. Clear All tag will not remove disabled selected options
2. Select All option somehow went missing, and I've restored that and excluded disabled options from it's behavior.
3. Tags for disabled options will now be disabled also.

fix(dropdown): selections and disabled options

---

src/components/global/header/headerFlyout.scss
src/components/global/header/headerLink.scss
src/components/global/localNav/localNav.scss
src/components/global/localNav/localNavLink.scss
src/components/reusable/card/vitalCard.scss
src/components/reusable/errorBlock/errorBlock.scss
src/components/reusable/modal/modal.scss
src/components/reusable/pagination/pagination-navigation-buttons.scss
src/components/reusable/sideDrawer/sideDrawer.scss
src/components/reusable/table/table-footer.scss
src/stories/sampleCardComponents/vitalCard.scss

Windows display scaling values other than 100% can cause viewport size/media query calculation issues. Our max-width queries had a "gap" of 1px where styles could potentially not be applied. Making them more precise erases that gap. Ex: 671.999px (42rem - .001px) vs 671px (42rem - 1px).
Ref: https://stackoverflow.com/a/63647803/23719206

fix: adjust max-width media query values to be more precise

---

custom-elements.json
src/components/reusable/dropdown/dropdown.stories.js
src/components/reusable/dropdown/dropdown.ts
src/components/reusable/pagination/pagination-page-size-dropdown.ts
src/stories/forms.stories.js

Adds programmable open direction with new `openDirection` prop on dropdown -- defaults to `auto`.
Available in the Form and Dropdown stories.
- [Dropdown -- Directional Control](https://deploy-preview-470--shidoka-applications.netlify.app/?path=/story/components-dropdown--directional-control) story shows `'auto'`, `'up'` and `'down'` options for the new `openDirection` prop.
- [Form Pattern](https://deploy-preview-470--shidoka-applications.netlify.app/?path=/story/patterns-forms--default) now contains down, auto, and up options
- Go to the [Dropdown -- Single](https://deploy-preview-470--shidoka-applications.netlify.app/?path=/story/components-dropdown--single) story and select an option from the `openDirection` controls dropdown to observe different directions

feat: programmable directionality of dropdown open

---

src/components/reusable/dropdown/dropdown.scss

Prevent short text cutoff as [seen in this report](https://teams.microsoft.com/l/message/19:m15yXA3kC7fl9TvnIML-6DxhfDtwyoLJMu0nVAeddXQ1@thread.tacv2/1749145531724?tenantId=f260df36-bc43-424c-8f44-c85226657b01&groupId=6097bcb7-eb77-4588-9226-1430b9c803ab&parentMessageId=1749145531724&teamName=Shidoka%20Design%20System&channelName=General&createdTime=1749145531724).

fix(dropdown): add min-width to options menu

---

src/components/reusable/toggleButton/toggleButton.ts

Fixes  user reported error
`TypeError: this._validate is not a function
at s._onUpdated (../../../node_modules/@kyndryl-design-system/src/common/mixins/form-input.ts:92:14)
at s.updated (../../../node_modules/@kyndryl-design-system/src/components/reusable/toggleButton/toggleButton.ts:122:10)
at s._$AE (../../../node_modules/@kyndryl-design-system/node_modules/lit-element/node_modules/@lit/reactive-element/reactive-element.js:6:5137)
at s.performUpdate (../../../node_modules/@kyndryl-design-system/node_modules/lit-element/node_modules/@lit/reactive-element/reactive-element.js:6:4917)
at scheduleUpdate (../../../node_modules/@kyndryl-design-system/node_modules/lit-element/node_modules/@lit/reactive-element/reactive-element.js:6:4499)
at s._$Ej …

fix(toggleButton): missing _validate function

---

src/components/reusable/widget/gridstack.stories.js
src/components/reusable/widget/sample/gridstack.newWidget.sample.ts
src/components/reusable/widget/sample/gridstack.newWidget.scss

Added color preset pattern in Grid/Add widget/SideDrawer(Settings)
[AB#2097838](https://dev.azure.com/Kyndryl/f7f7ab25-06ec-43dc-902d-dee2e157cebd/_workitems/edit/2097838)
[Figma](https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=34761-21839&m=dev)

fix(grid): added color preset pattern

---

src/components/reusable/dropdown/dropdown.ts

**On Safari** - Clicking on checkbox on dropdown options was closing the dropdown options
RCA : In Safari , click on `kyn-checkbox` considers outside interaction which causes the closing panel without checked checkbox. 
[AB#2319652](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2319652)
https://github.com/kyndryl-design-system/shidoka-applications/issues/491
NA

fix(dropdown): checkbox click fix on Safari

---

src/components/reusable/dropdown/dropdownOption.scss
src/components/reusable/dropdown/dropdownOption.ts

Dropdown panel: info icon placement to the right
[AB#2330799](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2330799)
[Link here](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2311739)
(if any)

fix(dropdown): info icon placement update

---

src/components/global/header/headerCategory.scss

Placement of `@include typography.type-ui-03;` in scss styles was overriding the desired font-weight (500) and setting it to the default font-weight for that typography (400).

fix(header category): heading font-weight

---

src/common/helpers/flatpickr.ts
src/common/scss/shidoka-flatpickr-theme.scss
src/components/reusable/datePicker/datepicker.ts
src/components/reusable/daterangepicker/daterangepicker.ts
src/components/reusable/timepicker/timepicker.ts

- __Issue__: When developers set `defaultDate` to a string value (e.g., '2024-07-02') from backend databases, the date wasn't showing in the date input field
- __Root Cause__: Components weren't properly handling dynamic data that arrives after component initialization
- __Impact__: Affected DatePicker, DateRangePicker, and TimePicker components
- __Issue__: Components needed to handle scenarios where default values are set dynamically from API calls or database queries
- __Root Cause__: The components were only processing default values during initial setup, not when they changed later
- __Impact__: Poor user experience when working with dynamic data sources
- Our CSS hides the up/down arrows when .single-year is present but we weren’t toggling that class on open (or re-invoking …

fix(pickers): address db populated max/minDate, defaultDate issues

---

custom-elements.json
package-lock.json
package.json
src/common/helpers/gridstack.ts
src/components/reusable/button/button.scss
src/components/reusable/button/defs.ts
src/components/reusable/widget/gridstack.stories.js
src/components/reusable/widget/sample/gridstack.newWidget.sample.ts
src/components/reusable/widget/widget.scss
src/components/reusable/widget/widget.stories.js
src/components/reusable/widget/widget.ts
src/components/reusable/widget/widgetDragHandle.scss
src/components/reusable/widget/widgetGridstack.scss
src/components/reusable/widget/widgetGridstack.ts

Changes to support tighter density in girdstack dashboards.
- Widget
- Added `compact` and `removeHeader` props.
- Gridstack
- Added `compact` and `wholeWidgetDraggable` props.
- `compact` prop will cascade to child widgets.
- Grid will re-init when these new props change.
- Passing a custom `gridstackConfig` will override these new props.
- UI toggle for compact setting?

feat: gridstack and widget compact options

---

custom-elements.json
src/components/reusable/notification/notification.scss
src/components/reusable/notification/notification.stories.js
src/components/reusable/notification/notification.ts

_Two issues brought up during office hours regarding Toast Notification_:
1) alignment of toast title icon and title text
2) handling the absence of a description wasn't working as expected, leaving an awkward empty space below title -- fix this and add a specific class so the close button can be vertically aligned to the main title when description is not present. 
New variant provided in Notification/Toast gallery that shows with no description

fix(toast notification): alignment and handling absence of description

---

custom-elements.json
src/components/reusable/buttonGroup/buttonGroup.scss
src/components/reusable/buttonGroup/buttonGroup.stories.js
src/components/reusable/buttonGroup/buttonGroup.ts

1. Add `gap: 1px;` to kyn-button-group to delineate buttons from one another.
2. Set default `selectedIndex` to `0` so that the first button in the group is selected by default.
3. Update stories to reflect both above changes

fix(buttonGroup): gap, default selectedIndex

---

custom-elements.json
src/components/reusable/notification/notification.stories.js
src/components/reusable/notification/notification.ts

`target` for clickable notifications was static `"_blank"` and did not provide the user with the ability to open the clickable notification in the same tab. New prop added to address this issue.

feat(notification): add target prop to component, stories

---

src/components/reusable/notification/notification.ts

`on-card-click` origEvent details were not being cascaded up through `on-notification-click` even details the same as in the documented structure.

fix(notification): corrected click event detail structure

---

custom-elements.json
src/components/reusable/numberInput/numberInput.scss
src/components/reusable/numberInput/numberInput.stories.js
src/components/reusable/numberInput/numberInput.ts
src/stories/emptyState/emptyState.stories.js
src/stories/forms.stories.js

min-/max-/width were set on numberInput.scss in such a way that it was not filling the width of the containing parent div like other form inputs.
1. Adjusted styles to remove constraints and set max-width in the two storybook instances where `<kyn-number-input>` is used.
2. Addressed issue with labels wrapping -- consuming dev can now control the width of the component itself (which dictates the width of the label) and the width of the internal input, separately.
#266

fix(number input): remove width constraints, fill parent containing div

---

src/common/scss/menu-item.scss
src/components/reusable/dropdown/dropdown.scss

Icon token on hover was not being applied
On Windows machines (Edge tested), dropdown scrollbar is persistent, so it is still obscuring the dropdown option content.

fix(dropdown): pagination dropdown on windows w scrollbar

---

src/components/reusable/dropdown/dropdown.scss

Dropdown - Multiselect : `X` clear icon not visible on selected item 
[Link](https://github.com/kyndryl-design-system/shidoka-applications/issues/579)
NA

fix(dropdown): multiselect clear icon visibility fix

---

src/components/reusable/tabs/tabs.scss

Tabs border could disappear behind parent elements if they had a background color.
resolves #603 
Add a background color to any parent element of `kyn-tabs`, observe the underline doesn't disappear.

fix(tabs): contain z-index context to prevent border appearing behind parent elements

---

src/components/reusable/tabs/tab.scss

- quick token correction on vertical, ai-connected Tabs in hover state.
- target `::after` properly to set border-radius on vertical ai tabs

fix(tabs): vertical, ai-connected hover text color

---

src/common/scss/gradients.scss
src/components/reusable/sideDrawer/sideDrawer.scss

AI Modal : gradient background not getting applied due to some undefined root token 
https://shidoka-applications.netlify.app/?path=/story/components-modal--ai-connected&globals=theme:light

fix(Modal): ai background gradient fix
