- custom-elements.json
- package-lock.json
- package.json
- src/components/reusable/checkbox/checkbox.scss
- src/components/reusable/radioButton/radioButton.scss
- src/components/reusable/textArea/index.ts
- src/components/reusable/textArea/textArea.scss
- src/components/reusable/textArea/textArea.stories.js
- src/components/reusable/textArea/textArea.test.ts
- src/components/reusable/textArea/textArea.ts
- src/components/reusable/textInput/index.ts
- src/components/reusable/textInput/textInput.scss
- src/components/reusable/textInput/textInput.stories.js
- src/components/reusable/textInput/textInput.test.ts
- src/components/reusable/textInput/textInput.ts
- src/index.ts
- src/stories/forms.stories.js
- tsconfig.json
Add initial Text Input and Text Area components.
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1219791
Open the deploy preview and view Text Area, Text Input, and Forms.
> Text Input & Text Area

- custom-elements.json
- package-lock.json
- package.json
- src/components/reusable/textInput/textInput.ts
- src/components/reusable/toggleButton/index.ts
- src/components/reusable/toggleButton/toggleButton.scss
- src/components/reusable/toggleButton/toggleButton.stories.js
- src/components/reusable/toggleButton/toggleButton.test.ts
- src/components/reusable/toggleButton/toggleButton.ts
- src/index.ts
- src/stories/forms.stories.js
Add initial Toggle Button component.
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1221607
Open the Deploy Preview and view Toggle Button.
> Toggle Button

- custom-elements.json
- src/components/reusable/checkbox/checkbox.scss
- src/components/reusable/checkbox/checkbox.stories.js
- src/components/reusable/checkbox/checkbox.ts
- src/components/reusable/dropdown/dropdown.scss
- src/components/reusable/dropdown/dropdown.stories.js
- src/components/reusable/dropdown/dropdown.test.ts
- src/components/reusable/dropdown/dropdown.ts
- src/components/reusable/dropdown/dropdownOption.scss
- src/components/reusable/dropdown/dropdownOption.ts
- src/components/reusable/dropdown/index.ts
- src/components/reusable/textArea/textArea.scss
- src/components/reusable/textArea/textArea.ts
- src/components/reusable/textInput/textInput.scss
- src/components/reusable/textInput/textInput.ts
- src/components/reusable/toggleButton/toggleButton.ts
- src/index.ts
- src/stories/forms.stories.js
Added dropdown component with serachable and multi-select variants.
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1235200
- Dropdown component
- Dropdown Option component
- Searchable variant
- Multi-Select variant
- Accessibility
- Keyboard navigation
- Screen reader assistance messages
- Focus handling
- aria and role tags
Open the Deploy Preview and view the Dropdown and Forms sections. I'm fairly confident in the keyboard navigation and focus handling, but not super confident in the screen reader experience which I can't really test. Please be critical with this one.
> Dropdown Component

- src/components/reusable/textArea/textArea.ts
- src/components/reusable/textInput/textInput.ts
Fix the if/else structure for validation on text input and text area components. Previously it was not validating min/max unless required = true.
> fix: text inputs validation nesting

- custom-elements.json
- src/components/reusable/datePicker/datepicker.stories.js
- src/components/reusable/datePicker/datepicker.ts
- src/components/reusable/daterangepicker/daterangepicker.scss
- src/components/reusable/daterangepicker/daterangepicker.stories.js
- src/components/reusable/daterangepicker/daterangepicker.test.ts
- src/components/reusable/daterangepicker/daterangepicker.ts
- src/components/reusable/daterangepicker/index.ts
- src/components/reusable/timepicker/timepicker.ts
- src/index.ts
- src/stories/forms.stories.js
Date range picker type with native input type = "date". with basic validations with start and end date
UI Story : [1238186](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1238186)
> feat: Date Range picker

- custom-elements.json
- src/components/reusable/table/Table.stories.ts
- src/components/reusable/table/table-header.ts
- can go here
- left to do
(if any)
> fix(table): hidden header

- custom-elements.json
- src/components/reusable/table/Table.stories.ts
- src/components/reusable/table/table-head.ts
- src/components/reusable/table/table-header.scss
- src/components/reusable/table/table-header.ts
- can go here
- left to do
(if any)
> fix(table): fix sorting

- src/components/reusable/daterangepicker/daterangepicker.ts
- src/stories/forms.stories.js
fix : [bug #21](https://github.com/kyndryl-design-system/shidoka-applications/issues/21)
Date range picker bug : https://github.com/kyndryl-design-system/shidoka-applications/issues/21
1. Go to https://kyndryl-design-system.github.io/shidoka-applications/?path=/story/patterns-forms--default
2. Enter values inside Date range picker (start & end date)
3. Hit Submit button
4. Check console, it appears date range values in formData
> fix: Date range value not append properly to formdata

- custom-elements.json
- src/components/reusable/table/Table.ts
- src/components/reusable/table/data-table.stories.ts
- src/components/reusable/table/data-table.ts
- src/components/reusable/table/table-cell.scss
- src/components/reusable/table/table-cell.ts
- src/components/reusable/table/table-header.scss
- src/components/reusable/table/table.scss
- can go here
- left to do
(if any)
> feat(table): enable ellipsis and fix for delete action demo story

- custom-elements.json
- src/components/global/localNav/localNavLink.scss
- src/components/global/localNav/localNavLink.ts
Added a `disabled` prop to `local-nav-link` which applies disabled styles and prevents default on click. Closes #28
> fix(local-nav-link): add disabled prop, closes #28

- custom-elements.json
- src/components/reusable/dropdown/dropdown.stories.js
- src/components/reusable/dropdown/dropdown.ts
Listens to the `slotchange` event and executes the `resetSelection` function again, resolves #32
> fix(dropdown): reset value when options change, resolves #32

- custom-elements.json
- src/components/reusable/table/data-table.ts
- src/index.ts
- can go here
- left to do
(if any)
> fix(data-table): export data-table from the root

- custom-elements.json
- src/components/global/header/header-interactive.scss
- src/components/global/header/headerNav.scss
- src/components/reusable/overflowMenu/index.ts
- src/components/reusable/overflowMenu/overflowMenu.scss
- src/components/reusable/overflowMenu/overflowMenu.stories.js
- src/components/reusable/overflowMenu/overflowMenu.test.ts
- src/components/reusable/overflowMenu/overflowMenu.ts
- src/components/reusable/overflowMenu/overflowMenuItem.scss
- src/components/reusable/overflowMenu/overflowMenuItem.ts
- src/index.ts
Added the overflow menu and overflow menu item components.
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1391644/?view=edit
Open the deploy preview and review the overflow menu story and it's variants/controls.
> feat: overflow menu

- custom-elements.json
- src/components/global/localNav/localNav.stories.js
- src/components/global/localNav/localNavLink.scss
- src/components/global/localNav/localNavLink.ts
> fix(local-nav-link): wrap text by default

- custom-elements.json
- package-lock.json
- package.json
- src/components/reusable/tabs/index.ts
- src/components/reusable/tabs/tab.scss
- src/components/reusable/tabs/tab.ts
- src/components/reusable/tabs/tabPanel.scss
- src/components/reusable/tabs/tabPanel.ts
- src/components/reusable/tabs/tabs.scss
- src/components/reusable/tabs/tabs.stories.js
- src/components/reusable/tabs/tabs.test.ts
- src/components/reusable/tabs/tabs.ts
- src/index.ts
> feat: tabs

- custom-elements.json
- src/components/reusable/sideDrawer/index.ts
- src/components/reusable/sideDrawer/sideDrawer.scss
- src/components/reusable/sideDrawer/sideDrawer.stories.js
- src/components/reusable/sideDrawer/sideDrawer.test.ts
- src/components/reusable/sideDrawer/sideDrawer.ts
- src/index.ts
Drawer component
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1589760
- give slide in slide out animation using **allow-discrete** property of animation
> feat: Drawer component

- src/components/reusable/sideDrawer/sideDrawer.scss
- src/components/reusable/sideDrawer/sideDrawer.stories.js
- src/components/reusable/sideDrawer/sideDrawer.ts
- fixed side drawer body scroll when body content inside is too long
Resolved below issue :
> fix(drawer): scroll position for longer content

- custom-elements.json
- src/components/reusable/pagination/Pagination.ts
- src/components/reusable/pagination/pagination-items-range.ts
- can go here
- left to do
(if any)
> fix(pagination): fixed item ranges when there is no data

- custom-elements.json
- src/components/reusable/globalFilter/globalFilter.stories.js
- src/components/reusable/globalFilter/globalFilter.table.sample.ts
- can go here
- left to do
(if any)
> feat(filter): added global filter applied to table

- .github/workflows/chromatic.yml
- custom-elements.json
- src/components/reusable/checkbox/checkboxGroup.ts
- src/components/reusable/datePicker/datepicker.scss
- src/components/reusable/datePicker/datepicker.ts
- src/components/reusable/daterangepicker/daterangepicker.scss
- src/components/reusable/daterangepicker/daterangepicker.ts
- src/components/reusable/dropdown/dropdown.ts
- src/components/reusable/radioButton/radioButtonGroup.ts
- src/components/reusable/textArea/textArea.ts
- src/components/reusable/textInput/textInput.ts
- src/components/reusable/timepicker/timepicker.ts
- src/components/reusable/toggleButton/toggleButton.ts
Add CSS part for label on all form field components. Resolves #41
> feat(form-inputs): add css part for label

- custom-elements.json
- src/components/reusable/table/story-helpers/table-story.ts
- src/components/reusable/table/table-cell.scss
- src/components/reusable/table/table-cell.ts
- can go here
- left to do
(if any)
> style(table): added the option to set min-width of the table cell

- custom-elements.json
- src/components/reusable/globalFilter/globalFilter.stories.js
- src/components/reusable/table/data-table.stories.ts
- src/components/reusable/table/story-helpers/table-data.json
- src/components/reusable/table/story-helpers/ultils.ts
- src/components/reusable/table/table-body.ts
- src/components/reusable/table/table.stories.ts
- src/components/reusable/table/table.ts
- tsconfig.json
- can go here
- left to do
(if any)
> fix(table): multi selection and visual test with fixed data

- custom-elements.json
- src/components/reusable/dropdown/dropdown.stories.js
- src/components/reusable/dropdown/dropdown.ts
> fix(dropdown): add filterable search option

- custom-elements.json
- src/components/reusable/modal/modal.scss
- src/components/reusable/modal/modal.stories.js
- src/components/reusable/modal/modal.ts
- can go here
- left to do
(if any)
> feat(modal): added the 3rd cta

- custom-elements.json
- src/components/reusable/table/index.ts
- src/components/reusable/table/story-helpers/table-story.ts
- src/components/reusable/table/table-cell.scss
- src/components/reusable/table/table-cell.ts
- src/components/reusable/table/table-expanded-row.scss
- src/components/reusable/table/table-expanded-row.ts
- src/components/reusable/table/table-header-row.scss
- src/components/reusable/table/table-header-row.ts
- src/components/reusable/table/table-header.scss
- src/components/reusable/table/table-header.ts
- src/components/reusable/table/table-row.scss
- src/components/reusable/table/table-row.ts
- src/components/reusable/table/table.stories.ts
- src/components/reusable/table/table.ts
- can go here
- left to do
(if any)
> feat(table): added new feature - expanded and disabled rows

- custom-elements.json
- src/components/global/header/header-interactive.scss
- src/components/global/header/headerFlyout.ts
- src/components/global/header/headerNav.ts
- src/components/global/localNav/localNav.scss
- src/components/global/localNav/localNav.ts
- src/components/global/uiShell/uiShell.stories.js
- Remove blur from all overlays
- Header flyout menus open on click
- Local Nav Pin button rotate animation
> fix: flyout interactions

- custom-elements.json
- src/components/reusable/globalFilter/globalFilter.table.sample.ts
Fixed the global filter applied to table story.
- can go here
- left to do
(if any)
> docs(story): global filter applied to table story

- src/components/reusable/daterangepicker/daterangepicker.stories.js
- src/components/reusable/daterangepicker/daterangepicker.ts
- src/stories/forms.stories.js
- Added date time with Date range picker with story
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1707130
> feat(daterange-picker): Added date time with date range picker

- src/components/reusable/daterangepicker/daterangepicker.ts
- Force prop change to update element value inside date-range-picker component
> fix(daterangepicker): Force prop change to update element value

- src/components/global/header/headerCategory.scss
- src/components/global/header/headerDivider.scss
- src/components/global/header/headerFlyout.scss
Adjusted menu label text styles, padding, and divider margins.
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1769191/?view=edit
> fix(header): menu label style adjustments

- src/components/global/header/headerCategory.scss
- src/components/global/header/headerDivider.scss
- src/components/global/header/headerFlyout.scss
Reverts kyndryl-design-system/shidoka-applications#193
> Revert "fix(header): menu label style adjustments"

- src/components/reusable/table/table-row.scss
UX added hover / rollout color when table is not interactive
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1808774
> fix(data-table): Added hover on table row according to UX

- custom-elements.json
- src/components/reusable/numberInput/index.ts
- src/components/reusable/numberInput/numberInput.scss
- src/components/reusable/numberInput/numberInput.stories.js
- src/components/reusable/numberInput/numberInput.ts
- src/index.ts
- src/stories/forms.stories.js
Add Number Input component.
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1808763/?view=edit
> feat(number-input): add number input component

- src/components/reusable/table/table-row.scss
Change table roll-over color to --kd-color-background-inverse-hover as per UX updates (at 06th Aug 2024)
> style(table): Change table rollover color as per UX updates

- custom-elements.json
- src/components/reusable/modal/modal.stories.js
- src/components/reusable/modal/modal.ts
- can go here
- left to do
(if any)
> feat(modal): Added disabled option to secondary button

- custom-elements.json
- src/components/global/footer/footer.scss
- src/components/global/footer/footer.stories.js
- src/components/global/footer/footer.ts
- src/components/global/footer/footerLink.ts
- src/components/global/footer/footerNav.scss
- src/components/global/footer/footerNav.ts
Updated Footer styles to match [Figma](https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/Applications---Component-Library?node-id=10033-1598&m=dev).
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1869138
- Deprecated `kyn-footer-nav` and `kyn-footer-link`, to be removed in 2.0
> feat(footer): footer design updates

- custom-elements.json
- src/components/reusable/textArea/textArea.stories.js
- src/components/reusable/textArea/textArea.ts
Added aria-lable , aria-describedby for better readability on Text-area component.
**User Story**
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1907637
**Tasks**
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1907228/
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1907229/
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1907230/
> fix(textarea): accessibility enhancements

- custom-elements.json
- src/common/scss/form-input.scss
- src/components/reusable/dropdown/dropdown.scss
- src/components/reusable/dropdown/dropdown.stories.js
- src/components/reusable/dropdown/dropdown.ts
- src/components/reusable/tag/tag.ts
AAT fixes for dropdown
Story : https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1904495
> feat(dropdown): accessibility enhancements

- custom-elements.json
- src/components/reusable/datePicker/datepicker.stories.js
- src/components/reusable/datePicker/datepicker.ts
- src/components/reusable/daterangepicker/daterangepicker.stories.js
- src/components/reusable/daterangepicker/daterangepicker.ts
- src/components/reusable/numberInput/numberInput.stories.js
- src/components/reusable/numberInput/numberInput.ts
- src/components/reusable/textInput/textInput.stories.js
- src/components/reusable/textInput/textInput.ts
- src/components/reusable/timepicker/timepicker.stories.js
- src/components/reusable/timepicker/timepicker.ts
Accessibility enhancement for Number & Text Input, Time, Date & DateRange Picker
NA
> fix(Input): accessibility enhancements for Number & Text Input, Time, Date & DateRange Picker

- custom-elements.json
- src/components/reusable/checkbox/checkbox.scss
- src/components/reusable/radioButton/radioButton.scss
Radio and checkbox input and lable alignment fix
- can go here
> fix(RadioCheckbox): alignment fix

- src/common/scss/utility/swiper-shidoka.scss
- src/stories/carousel/carousel.stories.js
Update Swiper scrollbar styles to match Figma.
https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/Applications---Component-Library?node-id=16511-30483&node-type=instance&m=dev
> fix(carousel): swiper scrollbar styles

- custom-elements.json
- package-lock.json
- src/components/reusable/overflowMenu/overflowMenu.stories.js
- src/components/reusable/overflowMenu/overflowMenuItem.scss
- src/components/reusable/overflowMenu/overflowMenuItem.ts
- src/components/reusable/tag/tag.ts
- src/components/reusable/tooltip/tooltip.stories.js
- src/components/reusable/tooltip/tooltip.ts
Accessibility enhancements (Overflow,Tags, Tooltip)
[Link here (if applicable).](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2020161)
> feat: accessibility enhancements

- src/components/reusable/modal/modal.stories.js
- src/components/reusable/radioButton/radioButton.scss
- src/components/reusable/radioButton/radioButton.stories.js
- src/components/reusable/radioButton/radioButtonGroup.ts
https://github.com/kyndryl-design-system/shidoka-applications/issues/292
> fix(radio button): disable radio button

- custom-elements.json
- package-lock.json
- src/components/global/footer/footer.scss
- src/components/global/footer/footer.stories.js
Footer color token update
[TASK 2003565](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003565)
https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/branch/qMpff4GuFUEcsMUkvacS3U/Applications---Component-Library?node-id=20056-822964&m=dev
Dependancy PR 
https://github.com/kyndryl-design-system/shidoka-foundation/pull/76
> feat(footer): color token update

- src/components/reusable/checkbox/checkbox.scss
- src/components/reusable/radioButton/radioButton.scss
> fix: checkbox & radio label alignment

- custom-elements.json
- src/components/reusable/modal/modal.stories.js
- src/components/reusable/modal/modal.ts
- src/components/reusable/sideDrawer/sideDrawer.stories.js
- src/components/reusable/sideDrawer/sideDrawer.ts
Added an `on-open` event that fires when the modal & side drawer open.
> feat: add on-open event to modal & side drawer

- src/components/reusable/errorBlock/errorBlock.scss
Colour token updates for Error block.
[TASK 2003586](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003586)
[Error block](https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/branch/qMpff4GuFUEcsMUkvacS3U/Applications---Component-Library?node-id=17573-1554&m=dev)
> feat(error-block): colour token updates

- package-lock.json
- src/components/reusable/stepper/stepperItem.scss
- src/components/reusable/stepper/stepperItem.ts
- src/components/reusable/stepper/stepperItemChild.scss
- src/components/reusable/stepper/stepperItemChild.ts
Color token updates for Stepper
[TASK 2003574](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003574)
https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/branch/qMpff4GuFUEcsMUkvacS3U/Applications---Component-Library?node-id=13321-162554&m=dev
Color token updates for Stepper
Waiting for @Diana Gutierrez Berrocal  to create circle-filled icon .
> feat(stepper):  color token updates

- .vscode/settings.json
- src/components/reusable/dropdown/dropdown.scss
- src/components/reusable/dropdown/dropdown.ts
Dropdown Disable state : Placeholder, caption and invalid text are not grayed out
[BUG 2089084](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2089084)
NA
> fix(dropdown): disable state fix by reverting primary html structure

- src/stories/vitalCard.stories.js
Fix for PR: https://github.com/kyndryl-design-system/shidoka-applications/pull/351
Fixes [AB#2102137](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2102137)
> fix: vital card with title tooltip - separate story

- src/components/reusable/card/card.scss
Updated default and hover state color token
Changes done as per - [2.0 color test](https://kyndryl-my.sharepoint.com/:x:/r/personal/brian_patrick3_kyndryl_com/_layouts/15/doc2.aspx?sourcedoc=%7Bb1d2f480-e50c-4442-8e85-18e65341e603%7D&action=edit&activeCell=%27Sheet1%27!I16&wdinitialsession=0af86b70-9e65-1016-d1ac-446ed40feca7&wdrldsc=4&wdrldc=1&wdrldr=AccessTokenExpiredWarningGatekeeperCookieMismatch%2C)
> fix(Card): default and hover state color fix

- src/components/reusable/button/button.scss
- Updated AI secondary/outline text color tokens for hover/pressed states.
- Fixed outline style icon alignment.
fixes [AB#2112534](https://dev.azure.com/Kyndryl/f7f7ab25-06ec-43dc-902d-dee2e157cebd/_workitems/edit/2112534)
fixes [AB#2112547](https://dev.azure.com/Kyndryl/f7f7ab25-06ec-43dc-902d-dee2e157cebd/_workitems/edit/2112547)
> fix(button): ai text colors and outline icon alignment

- custom-elements.json
- package-lock.json
- package.json
- src/components/reusable/tabs/tabPanel.scss
- src/components/reusable/tabs/tabs.scss
- src/components/reusable/tabs/tabs.stories.js
- src/components/reusable/tabs/tabs.ts
In support of the AI chat pattern, added prop to make tab panels scrollable. Requires height control on the host element, which should usually be 100%.
fixes [AB#2113137](https://dev.azure.com/Kyndryl/f7f7ab25-06ec-43dc-902d-dee2e157cebd/_workitems/edit/2113137)
> feat(tabs): scrollable panels

- custom-elements.json
- src/components/reusable/sideDrawer/sideDrawer.scss
- src/components/reusable/sideDrawer/sideDrawer.stories.js
- src/components/reusable/sideDrawer/sideDrawer.ts
AI varient added for Side Drawer
[USER STORY 2109642](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2109642)
[Figma](https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=18947-757758&m=dev)
> feat(sidedrawer): added AI varient

- src/components/reusable/datePicker/datepicker.ts
- src/components/reusable/daterangepicker/daterangepicker.ts
- src/components/reusable/timepicker/timepicker.ts
fixes #397 
fixes [AB#2132841](https://dev.azure.com/Kyndryl/f7f7ab25-06ec-43dc-902d-dee2e157cebd/_workitems/edit/2132841)
Error was occurring for dev who raised the Issue because, when datepicker (or timepicker or date-range picker) was required and the input value was empty, the code was setting valueMissing=true in the validity state but potentially had no validation message if defaultErrorMessage was empty.
> fix(date-pickers): validation message when validity flags are true

- src/components/reusable/modal/modal.scss
- src/components/reusable/sideDrawer/sideDrawer.scss
Added the gradients for the AI background colors.
- Drawer: https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=26765-17515&m=dev
- Modal: https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=25934-548263&m=dev
> fix: modal and side drawer AI bg colors

- custom-elements.json
- src/common/scss/form-input.scss
- src/components/reusable/textArea/textArea.scss
- src/components/reusable/textArea/textArea.stories.js
- src/components/reusable/textArea/textArea.ts
- src/stories/ai/inputQuery.stories.js
- src/stories/ai/response.stories.js
- Added folder for AI patterns, moved response and inputQuery under there
- Common styles for form input components AI bg/border 
- Update input query pattern styles
- Use `<form>` in input query pattern
- Add `hideLabel` prop to text area
https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=26094-199714&p=f&m=dev
> fix(form-inputs): common styles for ai bg/border, update input query

- src/stories/ai/response.stories.js
Added list spacing class to the response pattern.
fixes [AB#2149345](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2149345)
Before:
After:
> fix(response-pattern): added list spacing class for response pattern

- src/components/reusable/tabs/tab.scss
Remove stray red border style from `.contained.ai-connected--false`
fixes #416 
[AB#2152210](https://dev.azure.com/Kyndryl/f7f7ab25-06ec-43dc-902d-dee2e157cebd/_workitems/edit/2152210)
> fix(tabs): issue 416 red border-left removed

- custom-elements.json
- src/stories/ai/response.stories.js
Added response Skeleton pattern.
path: AI -> Response -> Skeleton 
fixes [AB#2176778](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2176778)
> feat(AIResponseSkeleton): ai response skeleton

- package-lock.json
- package.json
- src/stories/ai/inputQuery.stories.js
Added Input query patterns for thinking and cancel/abort.
[AB#2213888](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2213888)
[Link here 
](https://www.figma.com/design/VMT5QHCt6rw9KQwzyheU7e/-NewAI---MVP-1--AI-Consultancy---Content-Builder--Copy-?node-id=11068-2&p=f&t=a6HhcSFoXddq3zdy-0)
> feat(ai-input-query): add thinking/cancel pattern

- src/components/reusable/fileUploader/fileUploader.scss
- src/components/reusable/fileUploader/fileUploader.ts
- src/components/reusable/fileUploader/fileUploaderListContainer.scss
Border and spacing changes for better user experience.
NA
[FileUplaoder](https://www.figma.com/design/rC5XdRnXVbDmu3vPN8tJ4q/2.1-Edinburgh?node-id=4385-46185&t=xghfFhLcVey251hW-0)
**Before**
**After**
> fix(file-uploader): border and spacing enhancement

- custom-elements.json
- src/components/reusable/sliderInput/sliderInput.scss
- src/components/reusable/sliderInput/sliderInput.stories.js
- src/components/reusable/sliderInput/sliderInput.ts
Slider Input Component Enhancement : Added button control varient.
[USER STORY 2252554](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2252554)
[Figma](https://www.figma.com/design/rC5XdRnXVbDmu3vPN8tJ4q/2.2-Edinburgh?node-id=5535-3096&m=dev)
(if any)
> feat(sliderinput): added button control varient

- package-lock.json
- package.json
Updated shidoka chart version
NA
> chore: update shidoka charts

- custom-elements.json
- package-lock.json
- src/components/reusable/widget/widget.scss
- src/components/reusable/widget/widget.stories.js
- src/components/reusable/widget/widget.ts
Add a dedicated slot for Widget footer content with a default simple flex layout.
> feat(widget): add footer slot

- src/components/reusable/dropdown/dropdown.scss
- src/components/reusable/dropdown/dropdownOption.scss
- src/components/reusable/widget/Gridstack.mdx
- Fix ellipsis text overflow
- Reduce height to 48px
> fix(dropdown-option): reduce height, fix overflow

- src/components/global/header/Header.stories.js
- src/components/global/header/header.ts
- src/components/global/localNav/localNav.stories.js
- src/components/reusable/badge/badge.stories.js
- src/components/reusable/breadcrumbs/breadcrumbs.stories.js
- src/components/reusable/globalFilter/globalFilter.sample.ts
- src/components/reusable/globalFilter/globalFilter.scss
- src/components/reusable/globalFilter/globalFilter.stories.js
- src/components/reusable/modal/modal.stories.js
- src/components/reusable/modal/modal.ts
- src/components/reusable/pagination/pagination.stories.js
- src/components/reusable/tag/tag.stories.js
- src/components/reusable/tag/tagGroup.stories.js
- src/components/reusable/widget/gridstack.stories.js
- src/stories/informationalCard.stories.js
✅  = updated
❓ = issue (inquired with Diana)
⏳ = requires additional UX
💻 = requires additional UI
~We need to update the Figma component with new button guides, so this will need to be updated across everything: the component, SB, and GB.~
~Need to update Figma component with new button guides. So this will need to be updated across everything.~
~There were updates made to the component. SB needs to be updated.~
__Note: there's still a discussion happening around the buttons, so we're going to leave the above Modal, Side Drawer, and Global Filter items as they are for now. The following have been updated in this PR:__
SB: Link in design tab should be the one for Component Viewer
Design is still the old one in SB.
~SB: Design Tab link is set to the data table component viewer.~ Diana …
> chore: ui design consistency audit (link updates)

- src/components/reusable/toggleButton/toggleButton.scss
- src/components/reusable/toggleButton/toggleButton.ts
* **Reflect attributes**: added `reflect: true` to `checked`, `small`, and `disabled` props.
* **Accessibility attributes**: on `<input>` added `role="switch"`, `aria-checked=${this.checked}`, and `aria-describedby=${statusId}`.
* **ID management**
* **Checked binding**: replaced the boolean attribute `?checked` with the property binding `.checked=${this.checked}`.
* **Label markup**: simplified `<label>` to output `${this.label}` directly (removed inner `<span>`).
* **Dual status spans**: kept the visually hidden `<span id=${statusId} class="label-text sr-only">…</span>` for screen‑readers, and the visible `<span aria-hidden="true" class="status-text">…</span>` for sighted users.
* **handleKeyDown**: control added to address inactive keypress ('Space' bar) control
* **Component Focus**: …
> fix(toggle button): accessibility audit

- custom-elements.json
- src/components/reusable/fileUploader/fileUploader.ts
Add support for per-file custom error messages on invalidFiles in the file uploader component.
> feat(file-uploader): add customErrorMsg attribute to invalidFiles

- custom-elements.json
- package-lock.json
- package.json
- src/components/global/header/headerLink.ts
Allows customizing the number of child links needed to show the search input in the header nav submenus.
https://kyndrylshidoka.ideas.aha.io/ideas/KSDESIGN-I-143
> feat(header-link): add searchThreshold prop

- src/components/reusable/widget/sample/gridstack.newWidget.sample.ts
visibility fix for color preset on fileuploader
(if any)
> fix(colorpreset): visibility fix for color preset on fileuploader

- src/components/reusable/dropdown/dropdown.scss
- src/components/reusable/dropdown/dropdown.stories.js
- src/components/reusable/dropdown/dropdown.ts
- src/components/reusable/sideDrawer/sideDrawer.scss
- src/stories/forms.stories.js
Dropdown- Placeholder token color update
SideDrawer - Should follow Modal backdrop
[AB#2319329](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2319329)
[AB#2319333](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2319333)
[Backdrop](https://www.figma.com/design/9Q2XfTSxfzTXfNe2Bi8KDS/Component-Viewer?node-id=1-346871&p=f&m=dev)
(if any)
> chore(fix): ui fixes as per Figma

- src/components/global/header/Header.stories.js
- src/components/global/header/headerNotificationPanel.ts
- src/components/reusable/blockCodeView/blockCodeView.ts
- src/components/reusable/button/Button.stories.js
- src/components/reusable/pagetitle/pageTitle.scss
- src/components/reusable/sideDrawer/sideDrawer.ts
- src/components/reusable/table/story-helpers/column-setting.sample.ts
- src/components/reusable/table/story-helpers/table.settings.sample.ts
- src/components/reusable/table/table.scss
- src/components/reusable/table/table.skeleton.ts
Updated secondary button kind prop  and Page Title AI tertiary as per UX
[Page Title](https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=28871-118521&m=dev)
[SideDrawer](https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=11552-26680&m=dev)
[Code View](https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=16748-11543&m=dev)
Flyout Notification
Table Column Setting
> fix(Sidedrawer): sidedrawer secondary button,pagetitle ai tertiary,code view collapse btn, flyout notification btn,table column setting btn as per UX 

- package-lock.json
- package.json
- src/components/reusable/widget/widgetGridstack.scss
- src/components/reusable/widget/widgetGridstack.ts
To match https://github.com/kyndryl-design-system/shidoka-foundation/pull/128
> fix(gridstack): 16px gap for sm breakpoint

- custom-elements.json
- src/components/reusable/checkbox/checkboxGroup.ts
- src/components/reusable/datePicker/datepicker.ts
- src/components/reusable/daterangepicker/daterangepicker.ts
- src/components/reusable/dropdown/dropdown.ts
- src/components/reusable/multiInputField/multiInputField.ts
- src/components/reusable/numberInput/numberInput.ts
- src/components/reusable/radioButton/radioButtonGroup.ts
- src/components/reusable/sliderInput/sliderInput.ts
- src/components/reusable/textArea/textArea.ts
- src/components/reusable/textInput/textInput.ts
- src/components/reusable/timepicker/timepicker.ts
- src/components/reusable/toggleButton/toggleButton.ts
Cleanup/add attribute information for form input components.
> docs: cleanup/add attribute information for form input components

- custom-elements.json
- src/components/reusable/dropdown/dropdown.ts
- src/components/reusable/dropdown/enhancedDropdown.stories.js
- src/components/reusable/dropdown/enhancedDropdownOption.scss
- src/components/reusable/dropdown/enhancedDropdownOption.ts
- src/components/reusable/dropdown/index.ts
Optional `enhancedDropdownOption` child component that can be 'swapped' in/out for current default `dropdownOption` based on boolean value `enhanced` (false by default).
[AB#2397936](https://dev.azure.com/Kyndryl/f7f7ab25-06ec-43dc-902d-dee2e157cebd/_workitems/edit/2397936)
[Figma](https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library-2.0?node-id=13361-476952&m=dev)
<br/>
> feat(enhanced dropdown): new dropdown child component

- src/components/reusable/dropdown/dropdown.ts
- src/components/reusable/dropdown/enhancedDropdown.stories.js
Fix chevron in ButtonAnchor story
> fix(enhanced dropdown): chevron in ButtonAnchor story

- custom-elements.json
- src/components/ai/sourcesFeedback/aiSourcesFeedback.stories.js
- src/components/ai/sourcesFeedback/aiSourcesFeedback.ts
[AB#2409963](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2409963)
[Figma](https://www.figma.com/design/STWRRCgjIeXAZlIrIOJeTF/Ai-Component-Library?node-id=32640-7254&m=dev)
> feat(sourcepanel): updated source card content

- src/components/reusable/radioButton/radioButton.scss
Updated token as per UX
[AB#2489976](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2489976)
[Figma](https://www.figma.com/design/qyPEUQckxj8LUgesi1OEES/Component-Library?node-id=4193-260555&m=dev).
> fix(radiobtn): token update

- src/common/helpers/flatpickr.ts
- src/common/helpers/flatpickrOverlayPosition.ts
- src/components/reusable/datePicker/datepicker.stories.js
fixes https://github.com/kyndryl-design-system/shidoka-applications/issues/591
> fix(datepicker): overlay positioning in modals, cleanup

- src/components/reusable/dropdown/dropdown.ts
fixes #594 
[AB#2519885](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2519885)
https://github.com/user-attachments/assets/331bef40-6fcb-430c-868c-349b793329f4
> fix(dropdown): multiselect selectall checkmark visibility fix

- custom-elements.json
- package-lock.json
- package.json
- src/components/reusable/card/card.scss
- src/components/reusable/card/card.stories.js
- src/components/reusable/card/card.ts
- src/components/reusable/tag/tag.scss
- src/components/reusable/tag/tag.skeleton.ts
- src/stories/ai/response.stories.js
Update foundation version to allow access to tokens necessary for updating User Response pattern to make it more prominent and delineated from AI response.
Adds `interaction` card `variant` option with minimal updates to card.ts logic, styles.
[Ai Component Library link](https://www.figma.com/design/STWRRCgjIeXAZlIrIOJeTF/Ai-Component-Library?node-id=31336-8421&m=dev)
[AB#2360115](https://dev.azure.com/Kyndryl/f7f7ab25-06ec-43dc-902d-dee2e157cebd/_workitems/edit/2360115)
**Additional** - fixes #608 Tag skeleton
> feat(AI User Response): `interaction` card variant, pattern token update
